template: |
  ## What’s Changed

  $CHANGES
version-resolver:
  default: minor
categories:
  - title: "🚀 Features"
    label: "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
