name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
template: |
  ## What’s Changed

  $CHANGES
version-resolver:
  default: minor
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
autolabeler:
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
      - "/bug/i"
      - "/bugfix/i"
  - label: "enhancement"
    branch:
      - '/feature\/.+/'
    title:
      - "/feature/i"
      - "/enhancement/i"
