packages:
  # Include all of the core configuration
  core: !include hydro.yaml

external_components:
  - source: github://pr#9174
    components: [update, http_request]

esphome:
  # This will allow for project identification,
  # configuration and updates.
  project:
    name: jhbruhn.hydro
    version: dev # This will be replaced by the github workflows with the `release` version

# This should point to the public location of the yaml file that will be adopted.
# In this case it is the core yaml file that does not contain the extra things
# that are provided by this factory yaml file as the user does not need these once adopted.
dashboard_import:
  package_import_url: github://jhbruhn/hydro/hydro.yaml@main

ota:
  - platform: http_request

http_request:

wifi:
  on_connect:
    - component.update: http_firmware_update

update:
  - platform: http_request
    name: Firmware Update
    id: http_firmware_update
    source: https://jhbruhn.github.io/hydro/firmware/hydro.manifest.json
    on_update_available:
      - if:
          condition:
            switch.is_on: auto_ota
          then:
            - globals.set:
                id: prevent_sleep
                value: "true"
            - update.perform:

switch:
  - platform: template
    id: auto_ota
    name: Auto Install Firmware Updates
    icon: "mdi:auto-download"
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
improv_serial:
