esphome:
  # This will allow for project identification,
  # configuration and updates.
  project:
    version: dev # This will be replaced by the github workflows with the `release` version

packages:
  # Include all of the core configuration
  core: !include hydro.distance-sensor.yaml
  ota: !include module-ota.yaml
  factory: !include module-factory.yaml

# This should point to the public location of the yaml file that will be adopted.
# In this case it is the core yaml file that does not contain the extra things
# that are provided by this factory yaml file as the user does not need these once adopted.
dashboard_import:
  package_import_url: github://jhbruhn/hydro/hydro.distance-sensor.yaml@main

update:
  - platform: http_request
    id: !extend http_firmware_update
    source: https://jhbruhn.github.io/hydro/firmware/hydro.distance-sensor.manifest.json
