esphome:
  # This will allow for project identification,
  # configuration and updates.
  project:
    name: jhbruhn.hydro
    version: dev # This will be replaced by the github workflows with the `release` version

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
improv_serial:
